"use client";

import React from "react";
import { Box, VStack, Heading, Text, SimpleGrid, Image } from "@chakra-ui/react";
import { motion } from "framer-motion";

const MotionBox = motion(Box);

const STEPS = [
  {
    title: "Solar Panels Capture Sunlight",
    description:
      "Solar panels convert sunlight into electricity using photovoltaic (PV) cells. Position them on rooftops or open areas for maximum exposure.",
    image: "/images/com.jpg",
  },
  {
    title: "Inverters Convert Power",
    description:
      "The electricity generated by panels is direct current (DC). Inverters convert DC into alternating current (AC) usable in your home or business.",
    image: "/images/system-design.jpg",
  },
  {
    title: "Battery Storage & Monitoring",
    description:
      "Excess power is stored in batteries for later use. Smart monitoring ensures energy efficiency and tracks system performance.",
    image: "/images/battery2.jpg",
  },
  {
    title: "Regular Maintenance Keeps System Efficient",
    description:
      "Clean panels, check wiring, and monitor battery health. Regular maintenance ensures long-lasting and optimal solar performance.",
    image: "/images/kwh.jpg",
  },
];

export default function HowItWorksSection() {
  return (
    <Box
      w="full"
      minH="100vh"
      position="relative"
      overflow="hidden"
      bgGradient="linear(to-b, #081513, #0b1d1a)"
      px={{ base: 6, md: 20 }}
      py={{ base: 20, md: 28 }}
    >
      {/* Background Glow */}
      <Box
        position="absolute"
        inset={0}
        bgGradient="radial(circle at top, rgba(255,255,0,0.05), transparent 70%)"
        filter="blur(80px)"
        zIndex={-2}
      />

      {/* Section Heading */}
      <VStack spacing={6} mb={12} textAlign="center">
        <Heading
          fontSize={{ base: "3xl", md: "5xl" }}
          color="yellow.400"
        >
          How Solar Works
        </Heading>
        <Text fontSize={{ base: "md", md: "xl" }} color="whiteAlpha.800">
          Learn how solar panels generate electricity and how to maintain them for optimal performance.
        </Text>
      </VStack>

      {/* Steps */}
      <SimpleGrid columns={{ base: 1, md: 2 }} spacing={12} alignItems="center">
        {STEPS.map((step, i) => (
          <MotionBox
            key={step.title}
            initial={{ opacity: 0, y: 40, scale: 0.95 }}
            whileInView={{ opacity: 1, y: 0, scale: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8, delay: i * 0.3 }}
            display="flex"
            flexDirection={{ base: "column", md: i % 2 === 0 ? "row" : "row-reverse" }}
            alignItems="center"
            gap={6}
          >
            {/* Image */}
            <Box flex="1" minH={{ base: "200px", md: "300px" }} rounded="2xl" overflow="hidden" shadow="2xl">
              <Image
                src={step.image}
                alt={step.title}
                objectFit="cover"
                w="100%"
                h="100%"
              />
            </Box>

            {/* Text */}
            <VStack flex="1" align={{ base: "center", md: "start" }} spacing={4}>
              <Heading fontSize={{ base: "xl", md: "2xl" }} color="yellow.400">
                {step.title}
              </Heading>
              <Text fontSize={{ base: "sm", md: "md" }} color="whiteAlpha.800" textAlign={{ base: "center", md: "left" }}>
                {step.description}
              </Text>
            </VStack>
          </MotionBox>
        ))}
      </SimpleGrid>

      {/* Bottom Info Strip */}
      <Box
        mt={16}
        textAlign="center"
        color="whiteAlpha.800"
        fontSize={{ base: "sm", md: "md" }}
      >
        <Text>
          Tip: Clean your solar panels regularly, check inverter indicators, and monitor battery levels for uninterrupted power supply.
        </Text>
      </Box>
    </Box>
  );
}
